# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 803445815da4a17a474215d38ee6d84d038b220a3231c499085f72b1426db2d8fdd1f92e1dabc46826ed54eeae8ad96526a4255cee5ca161806da98ffb24eb25

test:
  secret_key_base: 2006148a35aaaac2ee189553eb99ab4d062f191d060600f28734cc489b4a5ce2d64c2ccec63e43894da30ca9adac44aa9ea95347222cbd9b8102aed191e88427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
